apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: nvtkh6ls3-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:20ed54aaf92be99ca9bb51988e5e53787fe5d7a1@sha256:53833359896e3f6c539a8928d9826bc0964fec67cb65ae9309ca8908409a777f
          name: container-image
