apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: nvtkh6ls3-python
  janus-idp.io/tekton: nvtkh6ls3-python
  backstage.io/kubernetes-id: nvtkh6ls3-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nvtkh6ls3-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
